version: "3.8"
services:
  backend:
    image: "jsoon/springboot-react-fullstack:9.9.2022.22.20.41"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev